# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: http_client
generate:
  client: true
  models: true
output: client.gen.go
output-options:
  name-normalizer: ToCamelCaseWithInitialisms