# yaml-language-server: $schema=https://raw.githubusercontent.com/oapi-codegen/oapi-codegen/HEAD/configuration-schema.json
package: http_server
generate:
  chi-server: true
  models: true
  strict-server: true
output: server.gen.go
output-options:
  name-normalizer: ToCamelCaseWithInitialisms